# Generated by Django 5.0.2 on 2024-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='')),
                ('prenom', models.CharField(max_length=50, verbose_name='')),
                ('profession', models.CharField(max_length=50, verbose_name='')),
                ('ville_natalle', models.CharField(max_length=50, verbose_name='')),
                ('age', models.IntegerField(verbose_name='')),
                ('date_adesion', models.DateTimeField(verbose_name='')),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
    ]
