# Generated by Django 5.0.2 on 2024-03-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='test'),
        ),
    ]
