# Generated by Django 5.0.2 on 2024-03-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0002_alter_membres_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='age',
            field=models.IntegerField(verbose_name='AGE :'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='date_adesion',
            field=models.DateTimeField(auto_now_add=True, verbose_name="DATE D'ADESION :"),
        ),
        migrations.AlterField(
            model_name='membres',
            name='image',
            field=models.ImageField(upload_to=None, verbose_name='IMAGE :'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='NOM :'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='prenom',
            field=models.CharField(max_length=50, verbose_name='PÉNOM :'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='profession',
            field=models.CharField(max_length=50, verbose_name='PROFESSION :'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='ville_natalle',
            field=models.CharField(max_length=50, verbose_name='vILLE NATALE :'),
        ),
    ]
