# Generated by Django 5.0.2 on 2024-03-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0003_alter_membres_age_alter_membres_date_adesion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membres',
            old_name='ville_natalle',
            new_name='ville_natale',
        ),
    ]
