# Generated by Django 5.0.2 on 2024-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0004_rename_ville_natalle_membres_ville_natale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='image',
            field=models.ImageField(upload_to='media/images', verbose_name='IMAGE :'),
        ),
    ]
