# Generated by Django 5.0.2 on 2024-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0006_alter_membres_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='IMAGE :'),
        ),
    ]
