# Generated by Django 5.0.2 on 2024-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0007_alter_membres_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='image',
            field=models.ImageField(height_field=400, max_length=400, upload_to='images', verbose_name='IMAGE :'),
        ),
    ]
