# Generated by Django 5.0.2 on 2024-03-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0008_alter_membres_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membres',
            old_name='date_adesion',
            new_name='date_adhesion',
        ),
        migrations.AlterField(
            model_name='membres',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='IMAGE :'),
        ),
    ]
